#!/bin/bash
# Read log file from stdin
cat - | \
# Remove empty lines
sed '/^$/d' | \
# Split fields by tab
awk -F'\t' '{
    # Count requests per host
    requests[$1]++
}
END {
    # Print top 11 hosts by number of requests
    for (host in requests) {
        print host "\t" requests[host]
    }
}' | \
# Sort by number of requests in descending order
sort -k2nr | \
# Print top 11 hosts
head -n11
